# Setup
title:               Moya Writes Things 
tagline:             "a personal website"
url:                 https://moyapchen.github.io
  # baseurl:             ''
paginate:            5
paginate_path: "/blog/page:num/"
permalink:           pretty


# As a quick way for footnotes?
markdown: kramdown
# configure kramdown
kramdown:
  parse_block_html: true

# About/contact
author:
  name:              Moya Chen
  url:               https://linkedin.com/moyapchen
  email:             moya.p.chen+website_email@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
